EmployeeManager.CosmosDB.EFCore/Controllers/EmployeeManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmployeeManager.CosmosDB.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Cosmos;



namespace EmployeeManager.CosmosDB.Controllers
{
    [Authorize(Roles = "Manager")]
    public class EmployeeManagerController : Controller
    {

        private readonly AppDbContext db;

        public EmployeeManagerController(AppDbContext db)
        {
            this.db = db;
            db.Database.EnsureCreated();
        }


        public void FillCountries()
        {
            if (db.Countries.AsEnumerable().Count() == 0)
            {
                Country usa = new Country() { DocumentID = Guid.NewGuid(), CountryID = 1, Name = "USA" };
                Country uk = new Country() { DocumentID = Guid.NewGuid(), CountryID = 2, Name = "UK" };
                db.Countries.Add(usa);
                db.Countries.Add(uk);
                db.SaveChanges();
            }

            List<SelectListItem> countries = (from c in db.Countries select new SelectListItem() { Text = c.Name, Value = c.Name }).ToList();

            ViewBag.Countries = countries;
        }


        public IActionResult List()
        {
            var query = from e in db.Employees
                        orderby e.EmployeeID
                        select e;

            return View(query.ToList());
        }


        public IActionResult Insert()
        {
            FillCountries();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(Employee emp)
        {
            FillCountries();

            if (ModelState.IsValid)
            {
                Employee obj = (from e in db.Employees
                                where e.EmployeeID == emp.EmployeeID
                                select e).SingleOrDefault();

                if (obj == null)
                {
                    emp.DocumentID = Guid.NewGuid();
                    db.Employees.Add(emp);
                    db.SaveChanges();
                    ViewBag.Message = "Employee inserted successfully!";
                }
                else
                {
                    ViewBag.Message = "EmployeeID already exists!";
                }
            }
            return View(emp);
        }


        public IActionResult Update(string id)
        {
            FillCountries();

            Employee emp = db.Employees.Find(new Guid(id));

            return View(emp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Employee emp)
        {
            FillCountries();

            if (ModelState.IsValid)
            {
                Employee obj = db.Employees.Find(emp.DocumentID);
                obj.EmployeeID = emp.EmployeeID;
                obj.FirstName = emp.FirstName;
                obj.LastName = emp.LastName;
                obj.Title = emp.Title;
                obj.BirthDate = emp.BirthDate;
                obj.HireDate = emp.HireDate;
                obj.Country = emp.Country;
                obj.Notes = emp.Notes;
                db.SaveChanges();
                ViewBag.Message = "Employee updated successfully!";
            }
            return View(emp);
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(string id)
        {
            Employee emp = db.Employees.Find(new Guid(id));
            return View(emp);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string documentID)
        {
            Employee emp = db.Employees.Find(new Guid(documentID));

            db.Employees.Remove(emp);
            db.SaveChanges();

            TempData["Message"] = "Employee deleted successfully!";

            return RedirectToAction("List");
        }


    }
}

EmployeeManager.CosmosDB.EFCore/Views/EmployeeManager/Delete.cshtml
@model Employee


<h2>Delete Existing Employee</h2>

<h3 class="message">
    Warning : You are about to delete an employee record!
</h3>

<form asp-controller="EmployeeManager" asp-action="Delete" method="post">

    <input type="hidden" asp-for="DocumentID" />

    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="EmployeeID"></label> :
            </td>
            <td>
                @Model.EmployeeID
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="FirstName"></label> :
            </td>
            <td>
                @Model.FirstName
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="LastName"></label> :
            </td>
            <td>
                @Model.LastName
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Title"></label> :
            </td>
            <td>
                @Model.Title
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="BirthDate"></label> :
            </td>
            <td>
                @Model.BirthDate.ToString("dd MMMM yyyy")
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="HireDate"></label> :
            </td>
            <td>
                @Model.HireDate.ToString("dd MMMM yyyy")
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Country"></label> :
            </td>
            <td>
                @Model.Country
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Notes"></label> :
            </td>
            <td>
                @Model.Notes
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Delete</button>
            </td>
        </tr>
    </table>
</form>

<br /><br />

<a asp-controller="EmployeeManager" asp-action="List">Back to Employee Listing</a>

EmployeeManager.CosmosDB.EFCore/Views/EmployeeManager/Insert.cshtml
@model Employee


<h2>Insert New Employee</h2>

<h3 class="message">@ViewBag.Message</h3>

<form asp-controller="EmployeeManager" asp-action="Insert" method="post">
    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="EmployeeID"></label> :
            </td>
            <td>
                <input type="text" asp-for="EmployeeID" />
                <span asp-validation-for="EmployeeID" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="FirstName"></label> :
            </td>
            <td>
                <input type="text" asp-for="FirstName" />
                <span asp-validation-for="FirstName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="LastName"></label> :
            </td>
            <td>
                <input type="text" asp-for="LastName" />
                <span asp-validation-for="LastName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Title"></label> :
            </td>
            <td>
                <input type="text" asp-for="Title" />
                <span asp-validation-for="Title" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="BirthDate"></label> :
            </td>
            <td>
                <input type="date" asp-for="BirthDate" />
                <span asp-validation-for="BirthDate" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="HireDate"></label> :
            </td>
            <td>
                <input type="date" asp-for="HireDate" />
                <span asp-validation-for="HireDate" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Country"></label> :
            </td>
            <td>
                <select asp-for="Country" asp-items="@ViewBag.Countries">
                    <option value="">Please select</option>
                </select>
                <span asp-validation-for="Country" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Notes"></label> :
            </td>
            <td>
                <textarea asp-for="Notes" rows="5" cols="40"></textarea>
                <span asp-validation-for="Notes" class="message"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
            </td>
        </tr>
    </table>
</form>

<br /><br />

<a asp-controller="EmployeeManager" asp-action="List">Back to Employee Listing</a>

EmployeeManager.CosmosDB.EFCore/Views/EmployeeManager/List.cshtml
@model List<Employee>


<h2>List of Employees</h2>

<h3 class="message">@TempData["Message"]</h3>

<a asp-controller="EmployeeManager" asp-action="Insert" class="linkbutton">Insert</a>

<br />
<br />

@if (Model == null || Model.Count == 0)
{
    <div class="message">No data found.</div>
}
else
{
    <table border="1">
        <tr>
            <th>Employee ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Title</th>
            <th colspan="2">Actions</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.EmployeeID</td>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.Title</td>
                <td>
                    <a asp-controller="EmployeeManager"
                       asp-action="Update"
                       asp-route-id="@item.DocumentID" class="linkbutton">Update</a>
                </td>
                <td>
                    <a asp-controller="EmployeeManager"
                       asp-action="Delete"
                       asp-route-id="@item.DocumentID" class="linkbutton">Delete</a>
                </td>
            </tr>
        }
    </table>
}

EmployeeManager.CosmosDB.EFCore/Views/EmployeeManager/Update.cshtml
@model Employee


<h2>Update Existing Employee</h2>

<h3 class="message">@ViewBag.Message</h3>

<form asp-controller="EmployeeManager" asp-action="Update" method="post">

    <input type="hidden" asp-for="DocumentID" />

    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="EmployeeID"></label> :
            </td>
            <td>
                <input type="text" asp-for="EmployeeID" readonly="readonly" />
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="FirstName"></label> :
            </td>
            <td>
                <input type="text" asp-for="FirstName" />
                <span asp-validation-for="FirstName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="LastName"></label> :
            </td>
            <td>
                <input type="text" asp-for="LastName" />
                <span asp-validation-for="LastName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Title"></label> :
            </td>
            <td>
                <input type="text" asp-for="Title" />
                <span asp-validation-for="Title" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="BirthDate"></label> :
            </td>
            <td>
                <input type="date" asp-for="BirthDate" />
                <span asp-validation-for="BirthDate" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="HireDate"></label> :
            </td>
            <td>
                <input type="date" asp-for="HireDate" />
                <span asp-validation-for="HireDate" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Country"></label> :
            </td>
            <td>
                <select asp-for="Country" asp-items="@ViewBag.Countries"></select>
                <span asp-validation-for="Country" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Notes"></label> :
            </td>
            <td>
                <textarea asp-for="Notes" rows="5" cols="40"></textarea>
                <span asp-validation-for="Notes" class="message"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
            </td>
        </tr>
    </table>
</form>

<br /><br />

<a asp-controller="EmployeeManager" asp-action="List">Back to Employee Listing</a>